// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_cell_map
void test_cell_map(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int D, int K, bool zero_gamma, bool rand_gamma, int cellid);
RcppExport SEXP _SpaTM_test_cell_map(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP DSEXP, SEXP KSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP cellidSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< int >::type cellid(cellidSEXP);
    test_cell_map(counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, cellid);
    return R_NilValue;
END_RCPP
}
// BuildDiseaseAlpha
arma::mat BuildDiseaseAlpha(const arma::mat& a, const arma::uvec& disease);
RcppExport SEXP _SpaTM_BuildDiseaseAlpha(SEXP aSEXP, SEXP diseaseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type disease(diseaseSEXP);
    rcpp_result_gen = Rcpp::wrap(BuildDiseaseAlpha(a, disease));
    return rcpp_result_gen;
END_RCPP
}
// get_theta
arma::mat get_theta(const arma::mat& n_dk, const arma::mat& alpha);
RcppExport SEXP _SpaTM_get_theta(SEXP n_dkSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_theta(n_dk, alpha));
    return rcpp_result_gen;
END_RCPP
}
// get_phi
arma::mat get_phi(const arma::mat& n_wk, const arma::mat& beta);
RcppExport SEXP _SpaTM_get_phi(SEXP n_wkSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_phi(n_wk, beta));
    return rcpp_result_gen;
END_RCPP
}
// train_gtm
void train_gtm(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int K, int D, arma::mat& n_dk, arma::mat& n_wk, int num_threads, int maxiter, bool verbal, bool zero_gamma, bool rand_gamma, double thresh, int burnin);
RcppExport SEXP _SpaTM_train_gtm(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP n_dkSEXP, SEXP n_wkSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP threshSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    train_gtm(counts, celltypes, genes, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, burnin);
    return R_NilValue;
END_RCPP
}
// infer_topics_cpp
void infer_topics_cpp(const arma::sp_mat& counts, const arma::vec& celltypes, const arma::vec& genes, double& alpha, int K, int D, int M, arma::mat& n_dk, const arma::mat& phi, int num_threads, int maxiter, bool verbal, int burnin);
RcppExport SEXP _SpaTM_infer_topics_cpp(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP MSEXP, SEXP n_dkSEXP, SEXP phiSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    infer_topics_cpp(counts, celltypes, genes, alpha, K, D, M, n_dk, phi, num_threads, maxiter, verbal, burnin);
    return R_NilValue;
END_RCPP
}
// infer_gex_cpp
List infer_gex_cpp(const arma::sp_mat& counts, const arma::vec& celltypes, const arma::vec& genes, double& alpha, int K, int D, int M, arma::mat& n_dk, const arma::mat& phi, int num_threads, int maxiter, bool verbal, int burnin);
RcppExport SEXP _SpaTM_infer_gex_cpp(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP MSEXP, SEXP n_dkSEXP, SEXP phiSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(infer_gex_cpp(counts, celltypes, genes, alpha, K, D, M, n_dk, phi, num_threads, maxiter, verbal, burnin));
    return rcpp_result_gen;
END_RCPP
}
// test_RTM_cell
void test_RTM_cell();
RcppExport SEXP _SpaTM_test_RTM_cell() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_RTM_cell();
    return R_NilValue;
END_RCPP
}
// test_RTM_cellmap
void test_RTM_cellmap(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int D, int K, bool zero_gamma, bool rand_gamma, Rcpp::List& nbr_list, int print_cell, int loss_fun);
RcppExport SEXP _SpaTM_test_RTM_cellmap(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP DSEXP, SEXP KSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP nbr_listSEXP, SEXP print_cellSEXP, SEXP loss_funSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type nbr_list(nbr_listSEXP);
    Rcpp::traits::input_parameter< int >::type print_cell(print_cellSEXP);
    Rcpp::traits::input_parameter< int >::type loss_fun(loss_funSEXP);
    test_RTM_cellmap(counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, nbr_list, print_cell, loss_fun);
    return R_NilValue;
END_RCPP
}
// train_RTM
arma::vec train_RTM(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, Rcpp::List& nbr_list, const arma::mat& alpha, const arma::mat& beta, int K, int D, arma::mat& n_dk, arma::mat& n_wk, int num_threads, int maxiter, bool verbal, bool zero_gamma, bool rand_gamma, double thresh, double lr, double rho, int loss_fun, bool m_update, int burnin);
RcppExport SEXP _SpaTM_train_RTM(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP nbr_listSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP n_dkSEXP, SEXP n_wkSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP threshSEXP, SEXP lrSEXP, SEXP rhoSEXP, SEXP loss_funSEXP, SEXP m_updateSEXP, SEXP burninSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type nbr_list(nbr_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< int >::type loss_fun(loss_funSEXP);
    Rcpp::traits::input_parameter< bool >::type m_update(m_updateSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    rcpp_result_gen = Rcpp::wrap(train_RTM(counts, celltypes, genes, nbr_list, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, lr, rho, loss_fun, m_update, burnin));
    return rcpp_result_gen;
END_RCPP
}
// nbr_pred
arma::mat nbr_pred(arma::mat theta, arma::rowvec weights, double max_val, int loss_fun);
RcppExport SEXP _SpaTM_nbr_pred(SEXP thetaSEXP, SEXP weightsSEXP, SEXP max_valSEXP, SEXP loss_funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type max_val(max_valSEXP);
    Rcpp::traits::input_parameter< int >::type loss_fun(loss_funSEXP);
    rcpp_result_gen = Rcpp::wrap(nbr_pred(theta, weights, max_val, loss_fun));
    return rcpp_result_gen;
END_RCPP
}
// get_dist_cpp
NumericMatrix get_dist_cpp(NumericMatrix x);
RcppExport SEXP _SpaTM_get_dist_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(get_dist_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// test_stm_cell
void test_stm_cell();
RcppExport SEXP _SpaTM_test_stm_cell() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_stm_cell();
    return R_NilValue;
END_RCPP
}
// test_stm_cellmap
void test_stm_cellmap(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int D, int K, bool zero_gamma, bool rand_gamma, arma::vec& labels, int print_cell);
RcppExport SEXP _SpaTM_test_stm_cellmap(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP DSEXP, SEXP KSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP labelsSEXP, SEXP print_cellSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type print_cell(print_cellSEXP);
    test_stm_cellmap(counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, labels, print_cell);
    return R_NilValue;
END_RCPP
}
// train_stm
arma::mat train_stm(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, arma::vec& labels, const arma::mat& alpha, const arma::mat& beta, int K, int D, arma::mat& n_dk, arma::mat& n_wk, int num_threads, int maxiter, bool verbal, bool zero_gamma, bool rand_gamma, double thresh, double lr);
RcppExport SEXP _SpaTM_train_stm(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP labelsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP n_dkSEXP, SEXP n_wkSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP threshSEXP, SEXP lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    rcpp_result_gen = Rcpp::wrap(train_stm(counts, celltypes, genes, labels, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, lr));
    return rcpp_result_gen;
END_RCPP
}
// progress_bar
void progress_bar(double iter, int maxiter, double elbo, double train_acc, double val_acc);
RcppExport SEXP _SpaTM_progress_bar(SEXP iterSEXP, SEXP maxiterSEXP, SEXP elboSEXP, SEXP train_accSEXP, SEXP val_accSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type elbo(elboSEXP);
    Rcpp::traits::input_parameter< double >::type train_acc(train_accSEXP);
    Rcpp::traits::input_parameter< double >::type val_acc(val_accSEXP);
    progress_bar(iter, maxiter, elbo, train_acc, val_acc);
    return R_NilValue;
END_RCPP
}
// stm_torch_estep
double stm_torch_estep(arma::sp_mat& spe_counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int K, int D, bool zero_gamma, bool rand_gamma, arma::vec& labels, arma::mat& n_dk, arma::mat& n_wk, arma::mat& elbo_mat, int layers, Rcpp::List& weights, double& elbo, int num_threads, int burnin, bool dummy_topic, int cur_iter);
RcppExport SEXP _SpaTM_stm_torch_estep(SEXP spe_countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP labelsSEXP, SEXP n_dkSEXP, SEXP n_wkSEXP, SEXP elbo_matSEXP, SEXP layersSEXP, SEXP weightsSEXP, SEXP elboSEXP, SEXP num_threadsSEXP, SEXP burninSEXP, SEXP dummy_topicSEXP, SEXP cur_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type spe_counts(spe_countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type elbo_mat(elbo_matSEXP);
    Rcpp::traits::input_parameter< int >::type layers(layersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double& >::type elbo(elboSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< bool >::type dummy_topic(dummy_topicSEXP);
    Rcpp::traits::input_parameter< int >::type cur_iter(cur_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(stm_torch_estep(spe_counts, celltypes, genes, alpha, beta, K, D, zero_gamma, rand_gamma, labels, n_dk, n_wk, elbo_mat, layers, weights, elbo, num_threads, burnin, dummy_topic, cur_iter));
    return rcpp_result_gen;
END_RCPP
}
// test_mlp_forward
arma::mat test_mlp_forward(const arma::mat& X, int layers, Rcpp::List& weights, bool dummy_topic);
RcppExport SEXP _SpaTM_test_mlp_forward(SEXP XSEXP, SEXP layersSEXP, SEXP weightsSEXP, SEXP dummy_topicSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type layers(layersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type dummy_topic(dummy_topicSEXP);
    rcpp_result_gen = Rcpp::wrap(test_mlp_forward(X, layers, weights, dummy_topic));
    return rcpp_result_gen;
END_RCPP
}
// train_sgtm
void train_sgtm(arma::sp_mat& counts, arma::vec& celltypes, arma::vec& genes, const arma::mat& alpha, const arma::mat& beta, int K, int D, arma::mat& n_dk, arma::mat& n_wk, int batch_size, int num_threads, int maxiter, bool verbal, bool zero_gamma, bool rand_gamma, double thresh, int burnin, double lr, const double tau0, const double kappa, bool shuffle);
RcppExport SEXP _SpaTM_train_sgtm(SEXP countsSEXP, SEXP celltypesSEXP, SEXP genesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP KSEXP, SEXP DSEXP, SEXP n_dkSEXP, SEXP n_wkSEXP, SEXP batch_sizeSEXP, SEXP num_threadsSEXP, SEXP maxiterSEXP, SEXP verbalSEXP, SEXP zero_gammaSEXP, SEXP rand_gammaSEXP, SEXP threshSEXP, SEXP burninSEXP, SEXP lrSEXP, SEXP tau0SEXP, SEXP kappaSEXP, SEXP shuffleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type celltypes(celltypesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type genes(genesSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_dk(n_dkSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type n_wk(n_wkSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type verbal(verbalSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_gamma(zero_gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type rand_gamma(rand_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< const double >::type tau0(tau0SEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< bool >::type shuffle(shuffleSEXP);
    train_sgtm(counts, celltypes, genes, alpha, beta, K, D, n_dk, n_wk, batch_size, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, burnin, lr, tau0, kappa, shuffle);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpaTM_test_cell_map", (DL_FUNC) &_SpaTM_test_cell_map, 10},
    {"_SpaTM_BuildDiseaseAlpha", (DL_FUNC) &_SpaTM_BuildDiseaseAlpha, 2},
    {"_SpaTM_get_theta", (DL_FUNC) &_SpaTM_get_theta, 2},
    {"_SpaTM_get_phi", (DL_FUNC) &_SpaTM_get_phi, 2},
    {"_SpaTM_train_gtm", (DL_FUNC) &_SpaTM_train_gtm, 16},
    {"_SpaTM_infer_topics_cpp", (DL_FUNC) &_SpaTM_infer_topics_cpp, 13},
    {"_SpaTM_infer_gex_cpp", (DL_FUNC) &_SpaTM_infer_gex_cpp, 13},
    {"_SpaTM_test_RTM_cell", (DL_FUNC) &_SpaTM_test_RTM_cell, 0},
    {"_SpaTM_test_RTM_cellmap", (DL_FUNC) &_SpaTM_test_RTM_cellmap, 12},
    {"_SpaTM_train_RTM", (DL_FUNC) &_SpaTM_train_RTM, 21},
    {"_SpaTM_nbr_pred", (DL_FUNC) &_SpaTM_nbr_pred, 4},
    {"_SpaTM_get_dist_cpp", (DL_FUNC) &_SpaTM_get_dist_cpp, 1},
    {"_SpaTM_test_stm_cell", (DL_FUNC) &_SpaTM_test_stm_cell, 0},
    {"_SpaTM_test_stm_cellmap", (DL_FUNC) &_SpaTM_test_stm_cellmap, 11},
    {"_SpaTM_train_stm", (DL_FUNC) &_SpaTM_train_stm, 17},
    {"_SpaTM_progress_bar", (DL_FUNC) &_SpaTM_progress_bar, 5},
    {"_SpaTM_stm_torch_estep", (DL_FUNC) &_SpaTM_stm_torch_estep, 20},
    {"_SpaTM_test_mlp_forward", (DL_FUNC) &_SpaTM_test_mlp_forward, 4},
    {"_SpaTM_train_sgtm", (DL_FUNC) &_SpaTM_train_sgtm, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpaTM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
