# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_cell_map <- function(counts, celltypes, genes, alpha, beta, D, K, zero_gamma = FALSE, rand_gamma = TRUE, cellid = 1L) {
    invisible(.Call(`_SpaTM_test_cell_map`, counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, cellid))
}

get_theta <- function(n_dk, alpha) {
    .Call(`_SpaTM_get_theta`, n_dk, alpha)
}

get_phi <- function(n_wk, beta) {
    .Call(`_SpaTM_get_phi`, n_wk, beta)
}

train_gtm <- function(counts, celltypes, genes, alpha, beta, K, D, n_dk, n_wk, num_threads = 1L, maxiter = 100L, verbal = TRUE, zero_gamma = FALSE, rand_gamma = TRUE, thresh = 0) {
    invisible(.Call(`_SpaTM_train_gtm`, counts, celltypes, genes, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh))
}

infer_topics_cpp <- function(counts, celltypes, genes, alpha, K, D, M, n_dk, phi, num_threads = 1L, maxiter = 100L, verbal = TRUE) {
    invisible(.Call(`_SpaTM_infer_topics_cpp`, counts, celltypes, genes, alpha, K, D, M, n_dk, phi, num_threads, maxiter, verbal))
}

test_RTM_cell <- function() {
    invisible(.Call(`_SpaTM_test_RTM_cell`))
}

test_RTM_cellmap <- function(counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, nbr_list, print_cell = 5L, loss_fun = 0L) {
    invisible(.Call(`_SpaTM_test_RTM_cellmap`, counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, nbr_list, print_cell, loss_fun))
}

train_RTM <- function(counts, celltypes, genes, nbr_list, alpha, beta, K, D, n_dk, n_wk, num_threads = 1L, maxiter = 100L, verbal = TRUE, zero_gamma = FALSE, rand_gamma = TRUE, thresh = 0.00001, lr = 0.001, rho = 1000.0, loss_fun = 0L, m_update = TRUE) {
    .Call(`_SpaTM_train_RTM`, counts, celltypes, genes, nbr_list, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, lr, rho, loss_fun, m_update)
}

nbr_pred <- function(theta, weights, max_val = 1, loss_fun = 0L) {
    .Call(`_SpaTM_nbr_pred`, theta, weights, max_val, loss_fun)
}

get_dist_cpp <- function(x) {
    .Call(`_SpaTM_get_dist_cpp`, x)
}

test_stm_cell <- function() {
    invisible(.Call(`_SpaTM_test_stm_cell`))
}

test_stm_cellmap <- function(counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, labels, print_cell = 5L) {
    invisible(.Call(`_SpaTM_test_stm_cellmap`, counts, celltypes, genes, alpha, beta, D, K, zero_gamma, rand_gamma, labels, print_cell))
}

train_stm <- function(counts, celltypes, genes, labels, alpha, beta, K, D, n_dk, n_wk, num_threads = 1L, maxiter = 100L, verbal = TRUE, zero_gamma = FALSE, rand_gamma = TRUE, thresh = 0.00001, lr = 0.0001) {
    .Call(`_SpaTM_train_stm`, counts, celltypes, genes, labels, alpha, beta, K, D, n_dk, n_wk, num_threads, maxiter, verbal, zero_gamma, rand_gamma, thresh, lr)
}

progress_bar <- function(iter, maxiter, elbo, train_acc, val_acc) {
    invisible(.Call(`_SpaTM_progress_bar`, iter, maxiter, elbo, train_acc, val_acc))
}

mlp_forward <- function(X, layers, weights, dummy_topic = FALSE) {
    .Call(`_SpaTM_mlp_forward`, X, layers, weights, dummy_topic)
}

get_label_prob <- function(ndk_row, gamma_weight, gene_count, K, label, layers, weights, dummy_topic = FALSE) {
    .Call(`_SpaTM_get_label_prob`, ndk_row, gamma_weight, gene_count, K, label, layers, weights, dummy_topic)
}

stm_torch_estep <- function(spe_counts, celltypes, genes, alpha, beta, K, D, zero_gamma, rand_gamma, labels, n_dk, n_wk, elbo_mat, layers, weights, elbo, num_threads = 1L, iter = 0L, dummy_topic = FALSE) {
    .Call(`_SpaTM_stm_torch_estep`, spe_counts, celltypes, genes, alpha, beta, K, D, zero_gamma, rand_gamma, labels, n_dk, n_wk, elbo_mat, layers, weights, elbo, num_threads, iter, dummy_topic)
}

